name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Run Tests
        run: |
          echo "Running tests..."
          npm test
